server {
    listen 80;
    
    # 前端静态文件
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # try_files $uri $uri/ /index.html;  # Vue Router history模式必须加
    }
    
    # API请求转发到后端
    location /api/ {
        proxy_pass http://auto-vi:3000;  # 容器名直接当域名用！
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}