version: "3"

services:
  # 后端 NestJS
  auto-vi:
    build:
      context: ./auto-vi
    image: auto-vi:latest  # 先占位，后面说怎么填
    container_name: auto-vi
    restart: unless-stopped
    ports:
      - "3010:3000"   # 左边是NAS端口，右边是容器内端口
    environment:
      - NODE_ENV=development
      - PORT=3010
      - PUBLIC_BASE_URL=http://192.168.50.100:9444/api  
      - UPLOAD_DIR=/app/uploads/images
      
    volumes:
      - ./uploads:/app/uploads  # 本地开发测试当前docker-compose所在目录 上传文件持久化
      - ./data:/app/data      # 本地开发测试当前docker-compose所在目录 数据持久化

  # 前端 Vue
  vi-admin:
    build:
      context: ./vi-admin
    image: vi-admin:latest
    container_name: vi-admin
    restart: unless-stopped
    ports:
      - "9444:80"    # 访问 192.168.50.100:8080 就是你的前端
    depends_on:
      - auto-vi      # 等后端启动后再启动前端

# 显式声明网络，两个容器在同一网络里才能用容器名互访
# networks:
#   default:
#     name: vi-system-network
    
# volumes:
#   vi-system-uploads:
#     external: true    # 引用刚才手动创建的volume -> volumes: vi-system-uploads:/app/uploads